# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: time_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'time_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12time_service.proto\x12\x04time\"\r\n\x0bTimeRequest\".\n\x0cTimeResponse\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\x32\x46\n\x0bTimeService\x12\x37\n\x0eGetCurrentTime\x12\x11.time.TimeRequest\x1a\x12.time.TimeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEREQUEST']._serialized_start=28
  _globals['_TIMEREQUEST']._serialized_end=41
  _globals['_TIMERESPONSE']._serialized_start=43
  _globals['_TIMERESPONSE']._serialized_end=89
  _globals['_TIMESERVICE']._serialized_start=91
  _globals['_TIMESERVICE']._serialized_end=161
# @@protoc_insertion_point(module_scope)
